{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[33mW0430 09:10:29.160704 Reloader tf_logging.py:121] Found more than one graph event per run, or there was a metagraph containing a graph_def, as well as one or more graph events.  Overwriting the graph with the newest event.\n",
      "\u001b[0m\u001b[33mW0430 09:10:29.162032 Reloader tf_logging.py:121] Found more than one metagraph event per run. Overwriting the metagraph with the newest event.\n",
      "\u001b[0mTensorBoard 1.6.0 at http://Mikaels-MacBook-Pro.local:6006 (Press CTRL+C to quit)\n",
      "\u001b[33mW0430 09:27:15.005735 Reloader plugin_event_multiplexer.py:203] Deleting accumulator '.'\n",
      "\u001b[0m\u001b[33mW0430 09:28:15.054218 Reloader tf_logging.py:121] Found more than one graph event per run, or there was a metagraph containing a graph_def, as well as one or more graph events.  Overwriting the graph with the newest event.\n",
      "\u001b[0m\u001b[33mW0430 09:28:15.054873 Reloader tf_logging.py:121] Found more than one metagraph event per run. Overwriting the metagraph with the newest event.\n",
      "\u001b[0m\u001b[33mW0430 09:29:30.403751 Reloader plugin_event_multiplexer.py:203] Deleting accumulator '.'\n",
      "\u001b[0m\u001b[33mW0430 09:29:40.411296 Reloader tf_logging.py:121] Found more than one graph event per run, or there was a metagraph containing a graph_def, as well as one or more graph events.  Overwriting the graph with the newest event.\n",
      "\u001b[0m\u001b[33mW0430 09:29:40.411881 Reloader tf_logging.py:121] Found more than one metagraph event per run. Overwriting the metagraph with the newest event.\n",
      "\u001b[0m\u001b[33mW0430 09:29:45.419434 Reloader tf_logging.py:121] Found more than one graph event per run, or there was a metagraph containing a graph_def, as well as one or more graph events.  Overwriting the graph with the newest event.\n",
      "\u001b[0m\u001b[33mW0430 09:29:45.419875 Reloader tf_logging.py:121] Found more than one metagraph event per run. Overwriting the metagraph with the newest event.\n",
      "\u001b[0m\u001b[33mW0430 10:57:36.675978 Reloader plugin_event_multiplexer.py:203] Deleting accumulator '.'\n",
      "\u001b[0m\u001b[33mW0430 11:35:28.877658 Reloader tf_logging.py:121] Found more than one graph event per run, or there was a metagraph containing a graph_def, as well as one or more graph events.  Overwriting the graph with the newest event.\n",
      "\u001b[0m\u001b[31mE0430 11:35:29.722877 Thread-270 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/application.py\", line 271, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/plugins/image/images_plugin.py\", line 105, in _serve_image_metadata\n",
      "    images = self._multiplexer.Tensors(run, tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py\", line 359, in Tensors\n",
      "    return accumulator.Tensors(tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py\", line 442, in Tensors\n",
      "    return self.tensors_by_tag[tag].Items(_TENSOR_RESERVOIR_KEY)\n",
      "KeyError: 'input/image/1'\n",
      "\u001b[0m\u001b[31mE0430 11:35:29.724465 Thread-269 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/application.py\", line 271, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/plugins/image/images_plugin.py\", line 105, in _serve_image_metadata\n",
      "    images = self._multiplexer.Tensors(run, tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py\", line 359, in Tensors\n",
      "    return accumulator.Tensors(tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py\", line 442, in Tensors\n",
      "    return self.tensors_by_tag[tag].Items(_TENSOR_RESERVOIR_KEY)\n",
      "KeyError: 'output/image/0'\n",
      "\u001b[0m\u001b[31mE0430 11:35:29.724851 Thread-268 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/application.py\", line 271, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/plugins/image/images_plugin.py\", line 105, in _serve_image_metadata\n",
      "    images = self._multiplexer.Tensors(run, tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py\", line 359, in Tensors\n",
      "    return accumulator.Tensors(tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py\", line 442, in Tensors\n",
      "    return self.tensors_by_tag[tag].Items(_TENSOR_RESERVOIR_KEY)\n",
      "KeyError: 'input/image/0'\n",
      "\u001b[0m\u001b[31mE0430 11:35:29.725191 Thread-271 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/application.py\", line 271, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/plugins/image/images_plugin.py\", line 105, in _serve_image_metadata\n",
      "    images = self._multiplexer.Tensors(run, tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py\", line 359, in Tensors\n",
      "    return accumulator.Tensors(tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py\", line 442, in Tensors\n",
      "    return self.tensors_by_tag[tag].Items(_TENSOR_RESERVOIR_KEY)\n",
      "KeyError: 'output/image/1'\n",
      "\u001b[0m\u001b[31mE0430 11:35:29.725419 Thread-273 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/application.py\", line 271, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/plugins/image/images_plugin.py\", line 105, in _serve_image_metadata\n",
      "    images = self._multiplexer.Tensors(run, tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py\", line 359, in Tensors\n",
      "    return accumulator.Tensors(tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py\", line 442, in Tensors\n",
      "    return self.tensors_by_tag[tag].Items(_TENSOR_RESERVOIR_KEY)\n",
      "KeyError: 'real_output/image/1'\n",
      "\u001b[0m\u001b[31mE0430 11:35:29.725615 Thread-272 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/application.py\", line 271, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/plugins/image/images_plugin.py\", line 105, in _serve_image_metadata\n",
      "    images = self._multiplexer.Tensors(run, tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py\", line 359, in Tensors\n",
      "    return accumulator.Tensors(tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py\", line 442, in Tensors\n",
      "    return self.tensors_by_tag[tag].Items(_TENSOR_RESERVOIR_KEY)\n",
      "KeyError: 'real_output/image/0'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[0m\u001b[31mE0430 11:35:29.747804 Thread-270 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/application.py\", line 271, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/plugins/image/images_plugin.py\", line 105, in _serve_image_metadata\n",
      "    images = self._multiplexer.Tensors(run, tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py\", line 359, in Tensors\n",
      "    return accumulator.Tensors(tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py\", line 442, in Tensors\n",
      "    return self.tensors_by_tag[tag].Items(_TENSOR_RESERVOIR_KEY)\n",
      "KeyError: 'input/image/0'\n",
      "\u001b[0m\u001b[31mE0430 11:35:29.761718 Thread-273 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/application.py\", line 271, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/plugins/image/images_plugin.py\", line 105, in _serve_image_metadata\n",
      "    images = self._multiplexer.Tensors(run, tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py\", line 359, in Tensors\n",
      "    return accumulator.Tensors(tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py\", line 442, in Tensors\n",
      "    return self.tensors_by_tag[tag].Items(_TENSOR_RESERVOIR_KEY)\n",
      "KeyError: 'input/image/1'\n",
      "\u001b[0m\u001b[31mE0430 11:35:29.771778 Thread-269 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/application.py\", line 271, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/plugins/image/images_plugin.py\", line 105, in _serve_image_metadata\n",
      "    images = self._multiplexer.Tensors(run, tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py\", line 359, in Tensors\n",
      "    return accumulator.Tensors(tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py\", line 442, in Tensors\n",
      "    return self.tensors_by_tag[tag].Items(_TENSOR_RESERVOIR_KEY)\n",
      "KeyError: 'real_output/image/0'\n",
      "\u001b[0m\u001b[31mE0430 11:35:29.780986 Thread-268 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/application.py\", line 271, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/plugins/image/images_plugin.py\", line 105, in _serve_image_metadata\n",
      "    images = self._multiplexer.Tensors(run, tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py\", line 359, in Tensors\n",
      "    return accumulator.Tensors(tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py\", line 442, in Tensors\n",
      "    return self.tensors_by_tag[tag].Items(_TENSOR_RESERVOIR_KEY)\n",
      "KeyError: 'output/image/1'\n",
      "\u001b[0m\u001b[31mE0430 11:35:29.785336 Thread-272 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/application.py\", line 271, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/plugins/image/images_plugin.py\", line 105, in _serve_image_metadata\n",
      "    images = self._multiplexer.Tensors(run, tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py\", line 359, in Tensors\n",
      "    return accumulator.Tensors(tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py\", line 442, in Tensors\n",
      "    return self.tensors_by_tag[tag].Items(_TENSOR_RESERVOIR_KEY)\n",
      "KeyError: 'real_output/image/1'\n",
      "\u001b[0m\u001b[31mE0430 11:35:29.786410 Thread-271 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/application.py\", line 271, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/plugins/image/images_plugin.py\", line 105, in _serve_image_metadata\n",
      "    images = self._multiplexer.Tensors(run, tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py\", line 359, in Tensors\n",
      "    return accumulator.Tensors(tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py\", line 442, in Tensors\n",
      "    return self.tensors_by_tag[tag].Items(_TENSOR_RESERVOIR_KEY)\n",
      "KeyError: 'output/image/0'\n",
      "\u001b[0m\u001b[31mE0430 11:35:29.797380 Thread-273 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/application.py\", line 271, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/plugins/image/images_plugin.py\", line 105, in _serve_image_metadata\n",
      "    images = self._multiplexer.Tensors(run, tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py\", line 359, in Tensors\n",
      "    return accumulator.Tensors(tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py\", line 442, in Tensors\n",
      "    return self.tensors_by_tag[tag].Items(_TENSOR_RESERVOIR_KEY)\n",
      "KeyError: 'input/image/1'\n",
      "\u001b[0m\u001b[31mE0430 11:35:29.800109 Thread-270 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/application.py\", line 271, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/plugins/image/images_plugin.py\", line 105, in _serve_image_metadata\n",
      "    images = self._multiplexer.Tensors(run, tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py\", line 359, in Tensors\n",
      "    return accumulator.Tensors(tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py\", line 442, in Tensors\n",
      "    return self.tensors_by_tag[tag].Items(_TENSOR_RESERVOIR_KEY)\n",
      "KeyError: 'input/image/0'\n",
      "\u001b[0m\u001b[31mE0430 11:35:29.815333 Thread-269 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/application.py\", line 271, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/plugins/image/images_plugin.py\", line 105, in _serve_image_metadata\n",
      "    images = self._multiplexer.Tensors(run, tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py\", line 359, in Tensors\n",
      "    return accumulator.Tensors(tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py\", line 442, in Tensors\n",
      "    return self.tensors_by_tag[tag].Items(_TENSOR_RESERVOIR_KEY)\n",
      "KeyError: 'real_output/image/0'\n",
      "\u001b[0m\u001b[31mE0430 11:35:29.824540 Thread-268 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/application.py\", line 271, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/plugins/image/images_plugin.py\", line 105, in _serve_image_metadata\n",
      "    images = self._multiplexer.Tensors(run, tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py\", line 359, in Tensors\n",
      "    return accumulator.Tensors(tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py\", line 442, in Tensors\n",
      "    return self.tensors_by_tag[tag].Items(_TENSOR_RESERVOIR_KEY)\n",
      "KeyError: 'output/image/1'\n",
      "\u001b[0m\u001b[31mE0430 11:35:29.830366 Thread-271 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/application.py\", line 271, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/plugins/image/images_plugin.py\", line 105, in _serve_image_metadata\n",
      "    images = self._multiplexer.Tensors(run, tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py\", line 359, in Tensors\n",
      "    return accumulator.Tensors(tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py\", line 442, in Tensors\n",
      "    return self.tensors_by_tag[tag].Items(_TENSOR_RESERVOIR_KEY)\n",
      "KeyError: 'output/image/0'\n",
      "\u001b[0m\u001b[31mE0430 11:35:29.834766 Thread-272 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/application.py\", line 271, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/plugins/image/images_plugin.py\", line 105, in _serve_image_metadata\n",
      "    images = self._multiplexer.Tensors(run, tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py\", line 359, in Tensors\n",
      "    return accumulator.Tensors(tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py\", line 442, in Tensors\n",
      "    return self.tensors_by_tag[tag].Items(_TENSOR_RESERVOIR_KEY)\n",
      "KeyError: 'real_output/image/1'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[0m\u001b[31mE0430 11:35:29.841837 Thread-270 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/application.py\", line 271, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/plugins/image/images_plugin.py\", line 105, in _serve_image_metadata\n",
      "    images = self._multiplexer.Tensors(run, tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py\", line 359, in Tensors\n",
      "    return accumulator.Tensors(tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py\", line 442, in Tensors\n",
      "    return self.tensors_by_tag[tag].Items(_TENSOR_RESERVOIR_KEY)\n",
      "KeyError: 'input/image/1'\n",
      "\u001b[0m\u001b[31mE0430 11:35:29.846095 Thread-273 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/application.py\", line 271, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/plugins/image/images_plugin.py\", line 105, in _serve_image_metadata\n",
      "    images = self._multiplexer.Tensors(run, tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py\", line 359, in Tensors\n",
      "    return accumulator.Tensors(tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py\", line 442, in Tensors\n",
      "    return self.tensors_by_tag[tag].Items(_TENSOR_RESERVOIR_KEY)\n",
      "KeyError: 'real_output/image/0'\n",
      "\u001b[0m\u001b[31mE0430 11:35:29.851349 Thread-269 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/application.py\", line 271, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/plugins/image/images_plugin.py\", line 105, in _serve_image_metadata\n",
      "    images = self._multiplexer.Tensors(run, tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py\", line 359, in Tensors\n",
      "    return accumulator.Tensors(tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py\", line 442, in Tensors\n",
      "    return self.tensors_by_tag[tag].Items(_TENSOR_RESERVOIR_KEY)\n",
      "KeyError: 'input/image/0'\n",
      "\u001b[0m\u001b[31mE0430 11:35:29.860890 Thread-268 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/application.py\", line 271, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/plugins/image/images_plugin.py\", line 105, in _serve_image_metadata\n",
      "    images = self._multiplexer.Tensors(run, tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py\", line 359, in Tensors\n",
      "    return accumulator.Tensors(tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py\", line 442, in Tensors\n",
      "    return self.tensors_by_tag[tag].Items(_TENSOR_RESERVOIR_KEY)\n",
      "KeyError: 'output/image/1'\n",
      "\u001b[0m\u001b[31mE0430 11:35:29.862380 Thread-271 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/application.py\", line 271, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/plugins/image/images_plugin.py\", line 105, in _serve_image_metadata\n",
      "    images = self._multiplexer.Tensors(run, tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py\", line 359, in Tensors\n",
      "    return accumulator.Tensors(tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py\", line 442, in Tensors\n",
      "    return self.tensors_by_tag[tag].Items(_TENSOR_RESERVOIR_KEY)\n",
      "KeyError: 'output/image/0'\n",
      "\u001b[0m\u001b[31mE0430 11:35:29.862895 Thread-272 _internal.py:88] Error on request:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 270, in run_wsgi\n",
      "    execute(self.server.app)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/serving.py\", line 258, in execute\n",
      "    application_iter = app(environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/application.py\", line 271, in __call__\n",
      "    return self.data_applications[clean_path](environ, start_response)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/werkzeug/wrappers.py\", line 308, in application\n",
      "    resp = f(*args[:-2] + (request,))\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/plugins/image/images_plugin.py\", line 105, in _serve_image_metadata\n",
      "    images = self._multiplexer.Tensors(run, tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py\", line 359, in Tensors\n",
      "    return accumulator.Tensors(tag)\n",
      "  File \"/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py\", line 442, in Tensors\n",
      "    return self.tensors_by_tag[tag].Items(_TENSOR_RESERVOIR_KEY)\n",
      "KeyError: 'real_output/image/1'\n",
      "\u001b[0m\u001b[33mW0430 11:37:33.971222 Reloader tf_logging.py:121] Found more than one metagraph event per run. Overwriting the metagraph with the newest event.\n",
      "\u001b[0m\u001b[33mW0430 13:02:39.300315 Reloader plugin_event_multiplexer.py:203] Deleting accumulator '.'\n",
      "\u001b[0m\u001b[33mW0430 13:02:39.300583 Reloader plugin_event_multiplexer.py:203] Deleting accumulator 'eval'\n",
      "\u001b[0m"
     ]
    }
   ],
   "source": [
    "!tensorboard --logdir=examplemodel --port=6006"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
